### PR TITLE
added checking for skip token auth environment var

### PR DESCRIPTION
**Pull request by hershilpatel**
Now you can set the `SKIP_TOKEN_AUTHENTICATION` environment variable to true to make all requests not require a valid token for authentication

### CODE REVIEW

**Comment by arscan** [comment]
Please rebase against master.

**Comment by hershilpatel** [comment]
Rebased onto master

**Review by okeefm — COMMENTED** [review]
Functionality looks good to me. Not sure why there are updates to the patients in this PR, however?

**Comment by hershilpatel** [comment]
Closing because rebase errors, now in new PR https://github.com/inferno-community/inferno-reference-server/pull/24

**Pull request closed without merging**
