### PR TITLE
Fi 355 make db start populated

### PR DESCRIPTION
**Pull request by hershilpatel**
Updated the docker-compose to use Dockerfile.database
Dockerfile.database now copies an initdb.sql file so the data will load on first start up
Updated README to reflect changes and be more accurate
deleted unecessary files

### CODE REVIEW

**Comment by arscan** [comment]
what is the command you use to generate `initdb.sql`?

**Comment by arscan** [comment]
Looks good to me too -- I deleted the volume, restarted, and it worked.  @hershilpatel could you please update the readme with a section on how to regenerate initdb.sql based on the current snapshot of what is in the database?  Mainly I'm just looking for the sql command documented :).  Once that's done I'll approve and merge.  Thanks!

**Comment by hershilpatel** [comment]
docker exec <DOCKER_CONTAINER_ID> pg_dump -U postgres postgres  > initdb.sql

**Comment by hershilpatel** [comment]
Should I include this command somewhere?

**Comment by okeefm** [comment]
You can do `docker-compose exec db` instead of looking up the container id @hershilpatel

**Comment by hershilpatel** [comment]
The docker compose still uses the Dockerfile.database, we have a copy step to copy initdb.sql into the correct folder

**Pull request merged**
