### PR TITLE
Fi 1093 change skip auth to specifiy token value

### PR DESCRIPTION
**Pull request by hershilpatel**
Removing the option to Skip Authentication and instead adding a env var to contain a custom bearer token.

To Test, set an env var CUSTOM_BEARER_TOKEN to value and try to enact a request with that bearer token.

### CODE REVIEW

**Comment by okeefm** [comment]
I think if this PR is rebased on `master`, it should rerun with Github Actions rather than Travis (which should pass)

**Review by okeefm — COMMENTED** [review]
Does what it should! Just two quick notes:

* It looks like some files that are already on `master` are getting re-added in this PR (specifically the GitHub Actions workflow files). It may be worth backing out the last merge commit and rebasing the entire branch on `master`?
* We should probably remove the old `SKIP_TOKEN_AUTHENTICATION` variable in `docker-compose.yml`, and possibly swap it out with a `CUSTOM_BEARER_TOKEN` (maybe something like `SAMPLE_TOKEN`)?

**Review by okeefm — APPROVED** [review]
Tested, looks good!

**Review by arscan — APPROVED** [review]
Works great!

**Pull request merged**
